### ISSUE TITLE
Add property activity_notes

### ISSUE THREAD

**Issue by ltaulell** [vkurup/python-tcxparser#21]
Hi, it's a feature request.

I'm using google Fit, in manual mode. As sport is not detected, activity_type contains 'Other', but my manual input is stored in Activity.Notes, from a picklist.

I propose this very little patch, to extract Notes from tcx file:

(in tcxparser.py, after activity_type)
```
    @property
    def activity_notes(self):
        return [x.text for x in self.root.xpath('//ns:Notes', namespaces={'ns': namespace})]
```
can be used same way as activity_type. Manual Fit tcx file as example (inline xml, not my clever idea, see attached zip file):

(sorry for the edit, I really should'nt post past 10PM)

[Fit_extracts.zip](https://github.com/vkurup/python-tcxparser/files/2395721/Fit_extracts.zip)

**Comment by vkurup** [comment]
Thank you for the feature request and the code snippet. I've added this and released a new version on PyPI: https://pypi.org/project/python-tcxparser/
