### ISSUE TITLE
Version bump on PyPi

### ISSUE THREAD

**Issue by slackline** [vkurup/python-tcxparser#26]
The version released on [PyPi is 1.0.0](https://pypi.org/project/python-tcxparser/) this is also the [current release here on GitHub](https://github.com/vkurup/python-tcxparser/releases/tag/1.0.0).

Since then a few very useful features have been included such as the inclusion of [`position.values()`](https://github.com/vkurup/python-tcxparser/commit/b2cdd4bf864618ea83715eccc751a9daa5224a2e) method.

I'm working on a package to convert [tcx2gpx](https://gitlab.com/nshephard/tcx2gpx) and it would be nice to have a newer version released so I don't have to pull from this git during installation.

Any chance of bumping the version and releasing to PyPi?

**Comment by vkurup** [comment]
Sure! Just released [1.1.0](https://pypi.org/project/python-tcxparser/1.1.0/). Thanks for the interest!

**Comment by slackline** [comment]
Brilliant, thanks.
