### ISSUE TITLE
No such child: Activities. Is my .tcx broken? Should this package also support Courses?

### ISSUE THREAD

**Issue by khink** [vkurup/python-tcxparser#28]
Hi,

I'm investigating a way to extract heart rate data from .tcx data, and was looking at this module for that. 

Unfortunately, on a first try, the parser fails:
```
Traceback (most recent call last):
  File "try_tcxparser.py", line 5, in <module>
    tcx = tcxparser.TCXParser('3A26185B.tcx')
  File "/home/kees/Projects/rides/python-tcxparser/tcxparser/tcxparser.py", line 18, in __init__
    self.activity = self.root.Activities.Activity
  File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 450, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: {http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Activities
```

My .tcx file starts with this:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
  <Courses>
    <Course>
      <Name>New Course</Name>
      <Lap>
        <TotalTimeSeconds>10896</TotalTimeSeconds>
        <DistanceMeters>65577.82</DistanceMeters>
        <BeginPosition>
          <LatitudeDegrees>0.0</LatitudeDegrees>
```

Unfortunately, http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 gives a 404, so i can't check if my .tcx is indeed broken. 

For what it's worth, i generated the .tcx file from a .fit file using gpsbabel. I looked in their issues, but there seem to be none related to "activities": https://github.com/gpsbabel/gpsbabel/issues?q=is%3Aissue+activities++

I googled for "tcx xml schema and found this: https://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd
From that source, it looks like both Activities and Courses are optional. Sure enough, when i replace `self.activity = self.root.Activities.Activity` in  `TCXParser.__init__` with `self.activity = self.root.Courses.Course`, parsing succeeds. 

Should the parser be adapted to also deal with Courses, and not require Activities?

**Comment by khink** [comment]
I just found out i can make gpsbabel write `Activities` instead of courses by setting the `courses=0` option: `gpsbabel -i garmin_fit -f 3A26185B.fit -o gtrnctr,course=0 -F 3A26185B.tcx`. Having Activities instead of Courses makes more sense for .tcx purposes, at least for mine.

This results in this tcx for the same .fit file:
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
  <Activities>
    <Activity Sport="Biking">
      <Id>2020-11-29T09:05:32Z</Id>
      <Lap StartTime="2020-11-29T09:05:32Z">
        <TotalTimeSeconds>10896</TotalTimeSeconds>
        <DistanceMeters>65577.82</DistanceMeters>
        <MaximumSpeed>10.252</MaximumSpeed>
        <Calories>0</Calories>
```
The parser can read this.

Seems like that is the best solution. Closing the issue.

**Comment by vkurup** [comment]
Thanks for doing the research and following up. This might help someone else in the future.

**Comment by MarcvdSluys** [comment]
Yep, this helped me - thanks!

Note that there is a typo in one of the two occurrences of the option above.  The correct syntax is `course=0`, not `courses=0`.
